services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    networks:
      portal-for-embroidery-net:
    environment:
      POSTGRES_DB: ${DB_NAME:-portal-for-embroidery}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_KEYCLOAK_DB: ${KEYCLOAK_DB_NAME:-keycloak}
      POSTGRES_KEYCLOAK_USER: ${KEYCLOAK_DB_USER:-keycloak_user}
      POSTGRES_KEYCLOAK_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_NAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: keycloak
    restart: always
    networks:
      portal-for-embroidery-net:
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${KEYCLOAK_DB_NAME:-keycloak}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER:-keycloak_user}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-keycloak_password}
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_PORT:-8081}
      KC_HEALTH_ENABLED: 'true'
    command: start --auto-build
    ports:
      - "${KEYCLOAK_PORT:-8081}:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      postgres:
        condition: service_healthy

  portal-for-embroidery-service:
    image: portal-for-embroidery-service:latest
    container_name: portal-for-embroidery-service
    restart: on-failure
    networks:
      portal-for-embroidery-net:
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    environment:
      SERVER_PORT: ${SERVER_PORT:-8080}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-portal-for-embroidery}
      DB_USERNAME: ${DB_USERNAME:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: http://keycloak:8080/realms/${KEYCLOAK_REALM:-portal-for-embroidery}
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

volumes:
  postgres_data:
  keycloak_data:

networks:
  portal-for-embroidery-net: