
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost/realms/portal-for-embroidery-local}
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:portal-for-embroidery-web}
            scope: openid,profile,email
            client-authentication-method: none
            authorization-grant-type: authorization_code
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost/realms/portal-for-embroidery-local}
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db.migration.v1/changelog.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: embroidery
  servlet:
    multipart:
      enabled: true